name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-upload: false
          skip-deploy: true
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_TEST }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_TEST }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
